### ISSUE TITLE
Converting models with multiple outputs (pp tiny_pose) fails. 'dict' object has no attribute 'append', With fix attached.

### ISSUE THREAD

**Issue by luan007** [PaddlePaddle/Paddle.js#261]
Hi,

Hit error below when using converter script.

```bash
python3 convertToPaddleJSModel.py --modelPath=tinypose_128x96/model.pdmodel --paramPath=tinypose_128x96/model.pdiparams --outputDir=tinypose_128x96/out
```

```bash
Organizing model variables info successfully.
A fetal error occured. Failed to convert model.
Traceback (most recent call last):
  File "/Users/doge/Desktop/learning/pp/Paddle.js/packages/paddlejs-converter/convertModel.py", line 491, in <module>
    convertToPaddleJSModel()
  File "/Users/doge/Desktop/learning/pp/Paddle.js/packages/paddlejs-converter/convertModel.py", line 431, in convertToPaddleJSModel
    appendConnectOp(fetch_targets)
  File "/Users/doge/Desktop/learning/pp/Paddle.js/packages/paddlejs-converter/convertModel.py", line 402, in appendConnectOp
    vars.append(outputVar)
AttributeError: 'dict' object has no attribute 'append'
```

Quick fix:

in `convertModel.py`, change line `402`
```python
#vars.append(outputVar)
vars[outputVar['name']] = outputVar
```

and the problem goes away.

Also, should `fetal` be `fatal`? 

Thanks!

**Comment by BenAnn** [comment]
Makesure your code is least.
We had fixed in #226

**Comment by BenAnn** [comment]
Makesure your code is latest.
We had fixed in #226

**Comment by luan007** [comment]
@BenAnn not quite?
please check for line `402` from `convertModel.py` in commit you've mentioned. (#226)

Thanks!

**Comment by BenAnn** [comment]
We had fixed in the master branch
![image](https://user-images.githubusercontent.com/17406160/147424402-851d7986-0560-4b27-9c90-689868bbee18.png)

**Comment by BenAnn** [comment]
We had fixed in the master branch

**Comment by luan007** [comment]
thanks!
