### ISSUE TITLE
TypeError: Object of type BlockDesc is not JSON serializable

### ISSUE THREAD

**Issue by luxu1220** [PaddlePaddle/Paddle.js#346]
使用 paddlejsconverter 对 paddlex 中的 PicoDet 模型转换时报如上的错误

**Comment by luxu1220** [comment]
#jsonDumpsIndentStr = json.dumps(opInfo, indent=2)
    #logModel(jsonDumpsIndentStr)

把之前报错的部分注释掉之后（上面两行），报如下错误

```
Traceback (most recent call last):
  File "/Users/teletraan/.pyenv/versions/3.7.9/envs/paddle/lib/python3.7/site-packages/convertModel.py", line 535, in main
    convertToPaddleJSModel(modelDir, modelName, paramsName, outputDir)
  File "/Users/teletraan/.pyenv/versions/3.7.9/envs/paddle/lib/python3.7/site-packages/convertModel.py", line 454, in convertToPaddleJSModel
    organizeModelVariableInfo(result)
  File "/Users/teletraan/.pyenv/versions/3.7.9/envs/paddle/lib/python3.7/site-packages/convertModel.py", line 176, in organizeModelVariableInfo
    varShape = excludeNegativeShape(v.shape)
  File "/Users/teletraan/.pyenv/versions/3.7.9/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1442, in shape
    return tuple(self.desc.shape())
RuntimeError: (Unavailable) Getting 'tensor_desc' is not supported by the _generated_var_44 type variable. (at /home/Paddle/paddle/fluid/framework/var_desc.cc:219)
```

**Comment by luxu1220** [comment]
我现在改用 paddle detection 训练出的模型来做转换，

命令为
```
paddlejsconverter --modelPath=work/PaddleDetection/output_inference/picodet_l_640_coco/model.pdmodel --paramPath=work/PaddleDetection/output_inference/picodet_l_640_coco/model.pdiparams --outputDir=js3
```
日志为
```
============Convert Model Args=============
modelPath: work/PaddleDetection/output_inference/picodet_l_640_coco/model.pdmodel
paramPath: work/PaddleDetection/output_inference/picodet_l_640_coco/model.pdiparams
outputDir: js3
enableOptimizeModel: 1
enableLogModelInfo: 0
sliceDataSize:4096
Starting...
Optimizing model...
python paddlelite version: 2.7.1
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0304 10:59:36.999784  5977 opt_base.cc:448] Error: This model is not supported, because 1 ops are not supported on 'arm'. These unsupported ops are: 'nearest_interp_v2'.

Optimizing model failed.

Converting model...
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Organizing model operators info...
Organizing model operators info successfully.
Organizing model variables info...
 transpose_7.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_6.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_0.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_16.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_18.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_10.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_12.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_1.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_4.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_6.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_2.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_14.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_5.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_0.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_9.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_3.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_8.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 transpose_8.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_4.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
 reshape2_2.tmp_0 tensor shape length > 4, 处理为丢弃头部shape 
Organizing model variables info successfully.
Model chunkNum set successfully.
Model FeedShape set successfully.
Dumping model structure to json file...
Dumping model structure to json file successfully
Output No.1 binary file, remain 2241621 param values.
Output No.2 binary file, remain 1193045 param values.
Output No.3 binary file, remain 144469 param values.
Output No.4 binary file, remain 0 param values.
Slicing data to binary files successfully. (4 output files and 3290197 param values)
Temporary files has been deleted successfully.
Converting model successfully.
============ALL DONE============
aistudio@jupyter-64630-3486734:~$ 
```
可以成功转换，但是模型输出很奇怪，是8个名为 transpose_{XXX}.tmp_0 的张量，正常应该是 bbox和类别，转换出的文件在附件里面。
[js3.zip](https://github.com/PaddlePaddle/Paddle.js/files/8182749/js3.zip)

**Comment by luxu1220** [comment]
@JingyuanZhang 麻烦看一下，🙏

**Comment by JingyuanZhang** [comment]
收到

**Comment by JingyuanZhang** [comment]
这个效果是符合预期的~我们对 多输出模型做了特殊处理，从 js 模型结构看，原始模型应该是 两个输出： box_coder 和 transpose2 算子，我们合并到 connect 算子中了。然后再 引擎中会进行拆分处理~

**Comment by luxu1220** [comment]
@JingyuanZhang 好的，谢谢，我再学习一下

**Comment by JingyuanZhang** [comment]
目前看算子都是支持的
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/10822846/156693941-76eb4b5f-4041-4e98-bb02-98d7107494c1.png">

<img width="597" alt="image" src="https://user-images.githubusercontent.com/10822846/156693855-ea738507-e79c-4d79-9023-b7fced0ea625.png">
如果有 推理问题，欢迎随时 开 issue 讨论，也可以加入我们 wx 技术交流群里 提问

**Comment by luxu1220** [comment]
贴个微信群的二维码？  [官网 ](https://paddlejs.baidu.com/) 下面的二维码过期了

**Comment by JingyuanZhang** [comment]
好的 一群已经满了，我拉你进二群哈

**Comment by JingyuanZhang** [comment]
![c0666136895cc7cbda4882d0a9aae99d](https://user-images.githubusercontent.com/10822846/156698243-bd4a9dad-a387-4226-889f-b809d8b63a18.png)

**Comment by luxu1220** [comment]
谢谢
