### ISSUE TITLE
paddleJs https 部署 Android 浏览器 （UC等）模型加载报错

### ISSUE THREAD

**Issue by a53769** [PaddlePaddle/Paddle.js#452]
如题，在使用官网检测模型对 humanStream 项目进行改造时，发现Android 浏览器在加载模型时抛出如下两个异常，导致无法加载。
```
webgl createProgram: sqrt -- Error: Error: compile: ERROR: 0:54: 'sqrt' : Name of a built-in function cannot be redeclared as function

Uncaught (in promise)  {
  "name": "TypeError",
  "message": "Cannot read property 'setProgram' of null",
  "stack": "TypeError: Cannot read property 'setProgram' of null
     at https://192.168.28.110:8866/main.js:251:32211
     at Array.forEach (<anonymous>)
     at e.runProgram (https://192.168.28.110:8866/main.js:251:32057)
     at t.execute (https://192.168.28.110:8866/main.js:262:8315)
     at t.executeOp (https://192.168.28.110:8866/main.js:262:44442)
     at t.executeOp (https://192.168.28.110:8866/main.js:262:44863)
     at t.executeOp (https://192.168.28.110:8866/main.js:262:44863)
     at t.executeOp (https://192.168.28.110:8866/main.js:262:44863)
     at t.executeOp (https://192.168.28.110:8866/main.js:262:44863)
     at t.executeOp (https://192.168.28.110:8866/main.js:262:44863)"
}
```

项目中仅替换了加载的模型，部署形式为https。使用的检测模型为 [picodet_xs_320_coco_lcnet_non_postprocess](https://paddledet.bj.bcebos.com/deploy/Inference/picodet_xs_320_coco_lcnet_non_postprocess.tar) 无后处理的轻量模型。

**Comment by a53769** [comment]
附，转换后模型 
链接：https://pan.baidu.com/s/1w6wUUCZ2YegoRStstnsRdg 
提取码：u1y8

**Comment by a53769** [comment]
详细排查后报错发生于 webgl backend 中，依赖版本：paddlejs-backend-webgl : ^1.1.19  paddlejs-core : ^2.1.17

**Comment by a53769** [comment]
报错代码块在 paddlejs-backend-webgl 中的 WebGLProgram.ts constructor 构造函数中。
报错的片元 fshader 代码如下：
 ```
 #version 300 es
            #ifdef GL_FRAGMENT_PRECISION_HIGH
            precision highp float;
            precision highp int;
        #else
            precision mediump float;
            precision mediump int;
        #endif      
        
            
        
        
        float fuse_op(float x) {
            float res = x;
            
            return res;
        }
    
            
        // 顶点shader透传的材质坐标
        in vec2 vCoord;
        out vec4 outColor;
        void setOutput(float result) {
            result = fuse_op(result);
            outColor.r = result;
        }
        void setPackedOutput(vec4 result) {
            outColor = result;
        }
        int calCeil(int a, int b) {
            return int(ceil(float(a) / float(b)));
        }
        
    
            int calMod(int a, int b) {
                return a - a / b * b;
            }
        
    
            int calDivision(int a, int b) {
                return a / b;
            }
        
    
    float tanh_calc(float num) {
        float res = (exp(2.0 * num) - 1.0) / (exp(2.0 * num) + 1.0);
        return res;
    }
    
    
    
            
            
    float sqrt(float x, float slope, float offset) {
        return sqrt(x);
    }

            
    uniform sampler2D texture_origin;
    
    #define getPixelsFromTexturePos_origin(pos) texture(texture_origin, pos)
    
    
            
        int layer_run_time = 0;
    
            
        
    vec2 _2d_shape_texture_out = vec2(float(80), float(40));
    
        
    ivec4 getOutputTensorPos() {
        vec2 outCoord = vCoord.xy * (_2d_shape_texture_out);
        int index = int(outCoord.x) + int(outCoord.y) * int(80);

        int n1 = int(index / 3200);
        int c1 = int(calMod(index, 3200) / 1600);
        int h1 = int(calMod(index, 1600) / 40);
        int w1 = calMod(index, 40);
        return ivec4(n1, c1, h1, w1);
    }
    
    
            
    // start函数
    void main(void) {
        // 输出数据
        float o = getPixelsFromTexturePos_origin(vCoord).r;
        float res = sqrt(o, float(1), float(0));
        setOutput(res);
    }
    
```

**Comment by a53769** [comment]
@JingyuanZhang 麻烦大佬看下这个问题
