### ISSUE TITLE
TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'

### ISSUE THREAD

**Issue by SomeAspy** [PaddlePaddle/Paddle.js#512]
I have been unable to install `@paddlejs/paddlejs-backend-nodegl` on my Arch Linux device.

I apologize for the lack of info, just let me know if you need anything more.

```
❯ pnpm i @paddlejs/paddlejs-backend-nodegl
 WARN  3 deprecated subdependencies found: har-validator@5.1.5, request@2.88.2, uuid@3.4.0
Packages: +121
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 311, reused 288, downloaded 0, added 0, done
node_modules/.pnpm/gl@4.9.2/node_modules/gl: Running install script, failed in 463ms
.../.pnpm/gl@4.9.2/node_modules/gl install$ prebuild-install || node-gyp rebuild
│ prebuild-install WARN install No prebuilt binaries found (target=21.2.0 runtime=node arch=x64 libc= platform=linux)
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@7.1.2
│ gyp info using node@21.2.0 | linux | x64
│ gyp info find Python using Python version 3.11.6 found at "/usr/bin/python3"
│ (node:54223) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
│ (Use `node --trace-deprecation ...` to show where the warning was created)
│ gyp ERR! UNCAUGHT EXCEPTION 
│ gyp ERR! stack TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'
│ gyp ERR! stack     at createConfigFile (/home/aiden/Documents/repos/aocr/node_modules/.pnpm/node-gyp@7.1.2/node_modules/node-gyp/lib/configure.js:117:21)
│ gyp ERR! stack     at /home/aiden/Documents/repos/aocr/node_modules/.pnpm/node-gyp@7.1.2/node_modules/node-gyp/lib/configure.js:84:9
│ gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:189:23)
│ gyp ERR! System Linux 6.6.8-arch1-1
│ gyp ERR! command "/home/aiden/.nvm/versions/node/v21.2.0/bin/node" "/home/aiden/Documents/repos/aocr/node_modules/.pnpm/node-gyp@7.1.2/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
│ gyp ERR! cwd /home/aiden/Documents/repos/aocr/node_modules/.pnpm/gl@4.9.2/node_modules/gl
│ gyp ERR! node -v v21.2.0
│ gyp ERR! node-gyp -v v7.1.2
│ gyp ERR! Node-gyp failed to build your package.
│ gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
└─ Failed in 463ms at /home/aiden/Documents/repos/aocr/node_modules/.pnpm/gl@4.9.2/node_modules/gl
 ELIFECYCLE  Command failed with exit code 7.
 ```

**Comment by SomeAspy** [comment]
Possible upstream issue with `gl`

**Comment by SomeAspy** [comment]
This was not an upstream issue of `gl`. This is an issue with the current package (suspected issue in question: https://github.com/stackgl/headless-gl/issues/271)
